### ISSUE TITLE
Add Brickimedia extensions

### ISSUE THREAD

**Issue by nemobis** [MWStake/nonwmf-extensions#25]
I believe a number of extensions from https://github.com/Brickimedia are missing.

When they're added here, maybe I can remove the explicit listing at https://www.openhub.net/p/mediawiki-extensions-other/enlistments

**Comment by hexmode** [comment]
I think I got them all.  Please close this unless I've missed some.

And thank you for letting me know!

**Comment by mary-kate** [comment]
So this should be reverted, because Brickimedia development moved from GitHub to WMF gerrit around the time Brickimedia web properties (well, mainly [Brickipedia, the free LEGO wiki](https://en.brickimedia.org/wiki/Main_Page)) moved to @ShoutWiki in 2017.
These super-legacy repositories are showing up on [codesearch](https://codesearch.wmcloud.org/) and confusing people as codesearch parses the @MWStake `nonwmf-extensions` and `nonwmf-skins` repo listings in its `write_config.py` file (in the `labs/codesearch` WMF gerrit repo; it took me a while to figure out that _this_ is why they're showing up!).

For future record, to clarify the situation:
**Skins**
* [Refreshed](https://www.mediawiki.org/wiki/Skin:Refreshed), Brickipedia's default skin, is maintained on WMF gerrit
* DeepSea no longer exists as a separate skin but instead as a Vector theme and a third-party wiki can install it by installing [the Theme extension](https://www.mediawiki.org/wiki/Extension:Theme) (which _**really**_ should be a core MW feature, but...)
* Custard, Lia and Quartz (which, btw, to my knowledge has no relation to the old Wikia skin with the same name) were dropped entirely

**Extensions**
* The Answers project, an attempt at reusing Wikia's answers-related extensions to provide a questions-and-answers feature, was dropped. The codebase never worked.
* [ARE](https://www.mediawiki.org/wiki/Extension:ArticleRatings), abbreviation of "ArticleRating extension", exists on WMF gerrit and is very much maintained and used on Brickipedia
* GlobalContribs repo exists on WMF gerrit but it should be archived and I think there was/is a Phab ticket about that? Either way IIRC the approach it uses to provide global contributions data is not very scalable and only works when you have so few databases you can count them with one or two hands' fingers at most...which, obviously, is not the case for ShoutWiki with its over 10k DBs. ShoutWiki implements the functionality in a more scalable manner with its (currently proprietary) LookupContribs extension. IIRC legoktm's GlobalContributions extension is a better implementation of Brickipedia's "GlobalContribs".
* NewTalkGlobal...suffers from the same issues as GlobalContribs IIRC. It queries *all* the DBs' local `user_newtalk` tables to bring the data together and obviously this doesn't scale. ShoutWiki historically had a custom, proprietary extension called SharedNewtalk to provide the same feature (cross-wiki "you have new messages" notifications) in a scalable manner, but we've since uninstalled that extension because we had several issues with it recently during major MW version upgrades. (It seems that core developers are really _intentionally_ making it harder and harder to query another DB from MW, whether the "remote" DB is or isn't a MW one. Sad.) Currently ShoutWiki implements cross-wiki new talk notifications via [Echo](https://www.mediawiki.org/wiki/Extension:Echo), or to be more specific, as a bunch of hacks/patches to Echo (three files in total) to remove WMF/CentralAuth-isms, as ShoutWiki does not use CentralAuth and thus neither `$wgConf`.
* NumberOfComments, which provides the `{{NUMBEROFCOMMENTS}}` magic word, appears to have its origins in Brickimedia/brickimedia#76. The [Comments extension](https://www.mediawiki.org/wiki/Extension:Comments), which was a hard dependency for NumberOfComments to begin with, included such a functionality since its "initial release" (by which I'm referring to the 14 September 2011 commit which is the 1st commit of the @wikimedia/mediawiki-extensions-Comments repository; actually Comments itself dates back to 2006 or so, that extension being one of the very first [social tools](https://www.mediawiki.org/wiki/Social_tools) to be ever written, but none of the social tools were open source at the time. Social tools became slowly FOSS with the initial public release of [SocialProfile](https://www.mediawiki.org/wiki/Extension:SocialProfile) in February 2008.) Anyway, in present-day Comments, the magic word is called `NUMBEROFCOMMENTSPAGE` and used like so: `{{NUMBEROFCOMMENTSPAGE:Page name here}}`
* Snippet was a Brickipedia-flavored extension to provide functionality identical to the [TextExtracts extension](https://www.mediawiki.org/wiki/Extension:TextExtracts). TextExtracts is used and maintained by the WMF. Discussion about the archival of the Snippet extension can be found at [T154220 on WMF Phabricator](https://phabricator.wikimedia.org/T154220).
* USERNAME, used to provide `{{USERNAME}}` as a pure PHP implementation...it's a bad idea, as anyone with an understanding of parser caching will tell you. "AbsolutelyMurderParserCacheBloodily" might be a more appropriate name for it, really. It's one of those things that'll work on a very low-traffic wiki but that's about it. That said, the _concept_ is much, much older and implemented on a vast majority of wikis via JavaScript and a **template** called _Template:USERNAME_ which provides something like a span element with a distinct class name, and the JS replaces the elements' contents with the value of `mw.config.get( 'wgUserName' )`. On [Uncyclopedia](https://en.uncyclopedia.co/), for example, [the template's](https://en.uncyclopedia.co/wiki/Template:USERNAME) contents are just `<span class="insertusername">{{{1|<insert name here>}}}</span>` so what the parser caches is the same for all users: `<span class="insertusername"><insert name here></span>` (unless someone calls the template with an argument, but even so, then the same argument would be cached for everyone) and JS takes care of replacing the text of that span with your user name.

I hope this helps. Please feel free to ping me here or on IRC should you have any further questions!
